name: Build and Deploy to AlwaysData

on:
  push:
    branches: [ "main" ]

env:
  NODE_VERSION: '23'

jobs:
  build:
    name: Build (Nuxt/Nitro)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Generate Nuxt internal files
        run: rm package-lock.json && npm i

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: output

  deploy:
    name: Deploy to AlwaysData (SSH)
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Debug artifact contents
        run: |
          echo "Listing downloaded artifact contents"
          ls -laR build || true

      - name: Copy files to server (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          # Copy the built artifact folder contents
          source: build
          target: ${{ secrets.REMOTE_PATH }}
          # Strip both the leading 'build' and 'artifact' directories
          strip_components: 1
          rm: true

      - name: restart application
        run: |
          err=$(curl -X POST --basic --user "${{secrets.ALWAYSDATA_TOKEN}} account=${{secrets.ALWAYSDATA_USER}}:" https://api.alwaysdata.com/v1/site/${{secrets.ALWAYSDATA_SITE_ID}}/restart/ &>2);
          if [[ "${err}" -eq "" ]]; then 
            echo "Redémarrage OK"
          else
            echo "Erreur : ${err}"
          fi
